<?php

namespace AppBundle\Repository;

/**
 * AddproductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddproductRepository extends \Doctrine\ORM\EntityRepository
{
}
