<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBy($agence)
    {

        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.user','u')
            ->leftJoin('u.agence','a')
            ->andWhere('a.name = :agence')
            ->setParameter('agence',$agence);

        return $qb->getQuery()->getResult();
    }
}
