<?php

namespace AppBundle\Repository;

/**
 * ProductPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
