<?php

namespace AppBundle\Repository;

/**
 * ProductPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPackageRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchOrderLineBy($agence)
    {

        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.user','u')
            ->leftJoin('u.agence','a')
            ->andWhere('a.name = :agence')
            ->setParameter('agence',$agence);

        return $qb->getQuery()->getResult();
    }
}
