<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBy($qualificationId){

        $qb = $this->createQueryBuilder('p');

            $qb
            ->select('p')
            ->leftJoin('p.qualifications','q')
            ->where('q.id = :qualificationId')
            ->setParameter('qualificationId', $qualificationId);

        return $qb->getQuery()->getResult();


    }
}
